### ISSUE TITLE
Basic getting started struggles on windows10

### ISSUE THREAD

**Issue by staxmanade** [manifoldjs/manifoldjs-windows10#16]
Using the sample manifest:
```
manifoldjs http://shiftr.azurewebsites.net/manifest.json -p windows10
```

If I open the generated solution `ShiftrAzurewebsitesNet\windows10\source\App.jsproj` and try to build I get:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		"10.0.10240.0" is not a supported value for TargetPlatformVersion. Please change it on the Project Property page.	App	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\JavaScript\Microsoft.VisualStudio.JavaScript.UAP.targets	82	

```

If I right-click on the project properties I can change the `Target version` to either `10.0.10586.0` or `10.0.14393.0` and same for `Min version`.

Any thoughts?

**Comment by boyofgreen** [comment]
Hi @staxmanade sorry for the delay.  We are about to push this [fix out for 0.7.5](https://github.com/manifoldjs/manifoldjs-windows10/blob/v0.1.8-development/lib/assets/project/App.jsproj) which makes it work on the anniversary update. But the work around is pretty simple.  in VS, right click on the project and "u nload" the project.  Then open up the project file as XML and change the TargetPlatformVersion to "10.0.14393.0" then reload the project.
