### ISSUE TITLE
Issues with installing PWAs on Windows 10 via preview.pwabuilder.com

### ISSUE THREAD

**Issue by nolanlawson** [manifoldjs/manifoldjs-windows10#29]
Rather than opening multiple issues, in case any of these are related or well-known, I'm opening a single issue to track problems I've observed using http://preview.pwabuilder.com:

1. It's only possible to install one PWA at a time (i.e. the second one overwrites the first).
2. Icons of the size 44x44, 50x50, and 150x150 are noted as required for Windows 10. (_"It appears that some image sizes used on Windows 10 are not in your Manifest. We will leave off any we can, and add defaults for any necessary images that are missing. Platforms affected:windows10."_) However, if these icons are *not* provided, then instead of downsampling from a larger size (e.g. 192x192), PWABuilder uses a placeholder icon.
3. Even if the 44x44, 50x50, and 150x150 icons are added, the resulting icon when pinned to the start menu doesn't show the app name, only the icon.

(For a demo of # 2, feel free to use https://mastodon.social, and for a demo of # 3, you can use https://toot.cafe.)

Are these known issues, and will these go away when we have native PWAs in 1803? Thanks.

**Comment by JudahGabriel** [comment]
This is now fixed with our new Chromium-based Edge platform for PWAs on Windows. Closing.
