### ISSUE TITLE
Resetting an installed PWA makes it impossible to install it again

### ISSUE THREAD

**Issue by SamueleDassatti** [manifoldjs/manifoldjs-windows10#31]
I tried to reset my PWA from Settings>Apps>Apps & Features>MyPWA>Advanced options>Reset but, instead of resetting, my app stopped showing in the all apps list and if I try to reinstall it from test_install file generated by PWA Builder I get this error: 0x80073CFB.

UPDATE: trying to sideload other PWAs also returns this error.

**Comment by lee-leonardo** [comment]
Apologies, but I'm not following. The flow mentioned above is this in the windows app store?

**Comment by SamueleDassatti** [comment]
No, it is in the Windows Settings app, the one you can open with the shortcut Win+I.

**Comment by JudahGabriel** [comment]
This is obsolete, as our Windows platform now uses Chromium-based Edge rather than the old legacy EdgeHTML web view. Closing.
