### ISSUE TITLE
Autopublish (-a) option is failing: getaddrinfo ENOTFOUND autopublish-api-prod.azurewebsites.net

### ISSUE THREAD

**Issue by NitradoJustus** [manifoldjs/manifoldjs-windows10#38]
Autopublish (-a) option is failing because the azure service is down. 

Afaik this was the only way to publish automatically to the Windows store in a build pipeline?

[Please redeploy the Azure Autopublish API! ](https://github.com/pwa-builder/pwabuilder-windows10/blob/c6347b0dcbed362ddeecbfe36b968b7e7b5b409f/lib/appPackage.js#L17:5)

**Comment by JudahGabriel** [comment]
We're working on automatic app ingestion, either via manifest property or CI/CD integration. We'll have something to announce later in the year.

FYI, this repository is being deprecated. To track this issue in the future, please open an issue on our [main PWABuilder repository](https://github.com/pwa-builder/pwabuilder/issues).
