### ISSUE TITLE
Rejected from windows app store for packageManagement capability issue

### ISSUE THREAD

**Issue by subhash279** [manifoldjs/manifoldjs-windows10#42]
![Screenshot 2020-11-18 at 20 16 24](https://user-images.githubusercontent.com/23074764/99545100-08f85080-29db-11eb-969f-d2507a3b93cd.png)
When I tried to submit to that app store, I got this as review.
Is there a way to remove this capability while packaging the pwa.

Thanks!

**Comment by JudahGabriel** [comment]
Hi @subhash279 ,

The good news is, [this is fixed](https://github.com/pwa-builder/PWABuilder/issues/1247). You just need to create a new package using PWABuilder, and this one no longer requires the packageManagement capability.

In the future, please open issues on the [main PWABuilder repo](https://github.com/pwa-builder/pwabuilder/issues).
