### ISSUE TITLE
PWA uninstalls after PC reset

### ISSUE THREAD

**Issue by kyleshay** [manifoldjs/manifoldjs-windows10#44]
Thanks for this project, it's been so easy and awesome to use to get into the app stores!

We're getting numerous reports from our users that they need to re-download/reinstall the PWA every time they reset their PC. 

Unfortunately I don't have any other information to provide, but could try to gather some metrics if you know what may be useful.

Is this something that anyone else is seeing? I haven't been able to pin down what could be causing this. 

--- 
Built with Chromium-based Edge
https://www.microsoft.com/en-us/p/destiny-item-manager-dim/9p8q2xrw9cv7
https://www.pwabuilder.com/?url=https%3A%2F%2Fapp.destinyitemmanager.com

**Comment by JudahGabriel** [comment]
You're the first report I've heard about this. 

Before I escalate this to the Edge group, forgive me but I haven't reset my PC in a long time. So let's first find out: Doesn't Windows reset [uninstall your apps](https://answers.microsoft.com/en-us/windows/forum/windows_10-update-winpc/where-is-the-list-of-uninstalled-apps-after/35567633-ecba-498f-9de9-53fee59554fb)? Looking at [this link](https://www.ubackup.com/windows-10/refresh-windows-10-without-losing-programs-4348.html), it seems that's the default behavior is to uninstall all apps.

**Comment by kyleshay** [comment]
Sorry, I should have clarified what I meant by 'reset'— we're getting reports that turning off and on their PC uninstalls the PWA app. 😬

**Comment by JudahGabriel** [comment]
We're certainly not seeing that on this end. I personally have a PWA in the Store, and have it installed for many months now, and have restarted many times, and haven't seen it get uninstalled.

**Comment by kyleshay** [comment]
Ah thanks for the response.

Hmm, this was built with the newer chromium based edge version- not sure if that makes a difference. We've had quite a few reports of it but it's not something everyone is seeing. I'll try to loop back around to them and see if I can get some more information about their setup.

Linking an issue for context: https://github.com/DestinyItemManager/DIM/issues/6446

**Comment by bhollis** [comment]
The sort of report we get from our users is as in that linked issue:

> Once installed app works absolutely fine, however after turning my PC off the app is completely uninstalling itself, even searching via the windows task bar doesn't find the app. I have to redownload the app from the store again (this has happened twice now)

**Comment by JudahGabriel** [comment]
I see that. @bhollis when you built the app from PWABuilder, did you change the start URL in PWABuilder's options dialog? I'm wondering if you're seeing some weirdness around app identity.

**Comment by JudahGabriel** [comment]
@kyleshay We've recently deployed some fixes to the PWABuilder Windows platform around app identity. I'm not sure this fixes your problem, but it may. I recommend repackaging with PWABuilder, uploading a new app version to the Store.

**Comment by kyleshay** [comment]
Thanks for the update! We'll get a build out this evening and report back within the week with what users are seeing.

Also, I believe our start URL is `/index.html?utm_source=homescreen` -- do you know why there might be a red border on that? I'm not seeing a message. Tooltip says relative or absolute? Our manifest is [pulled from here](https://app.destinyitemmanager.com/manifest-webapp-6-2018.json)

<img width="407" alt="Screen Shot 2021-03-22 at 8 10 53 PM" src="https://user-images.githubusercontent.com/424158/112087204-c55d5100-8b4a-11eb-9b06-65d2682c2dba.png">

Edit: Went ahead and submitted the app update. Will keep you posted!

**Comment by JudahGabriel** [comment]
@kyleshay Everything work for you? Safe to close this issue?

**Comment by kyleshay** [comment]
Sorry about not looping back! Yes, we've seen the reports drop. Seems to have resolved it. Thanks again!
