### ISSUE TITLE
Some users having trouble installing the PWA from the MS store

### ISSUE THREAD

**Issue by kyleshay** [manifoldjs/manifoldjs-windows10#45]
![Untitled](https://user-images.githubusercontent.com/30773815/105622649-98cbd800-5e2c-11eb-890e-4e37634aa5cc.png)

They're able to download other applications as expected, but are running into issues with the PWA. The app was using the Chromium-based edge PWA builder.

https://github.com/DestinyItemManager/DIM/issues/6463

**Comment by JudahGabriel** [comment]
I suspect the user doesn't have the new Edge installed. (Which also implies they have an outdated version of Windows installed.)

Can you confirm?

p.s. In the future, please open issues over at our [main repo](https://github.com/pwa-builder/pwabuilder), which gets more TLC. :-)

**Comment by JudahGabriel** [comment]
I see the user [fixed the issue](https://github.com/DestinyItemManager/DIM/issues/6463#issuecomment-777022460) after installing the latest Windows updates. (The latest Windows updates will install the necessary Edge dependencies.) Closing.
