### ISSUE TITLE
pwabuilder not support package ID with dash character.

### ISSUE THREAD

**Issue by MrMYHuang** [manifoldjs/manifoldjs-windows10#49]
My package ID is 40522Meng-YuanHuang.54781685684B5.
![image](https://user-images.githubusercontent.com/12458706/125740134-2f2041ac-eb89-47fb-9ac2-259ff4dbc78f.png)

Unfortunately, pwabuilder doesn't support this package ID:
![image](https://user-images.githubusercontent.com/12458706/125740052-05dbfff7-de2f-44c9-b099-bcf561cf2eb9.png)

By my experiment, if I remove the "-" character, pwabuilder will accept it. Please fix this problem. Thanks.

**Comment by JudahGabriel** [comment]
Thanks! I've merged your fix. We should have a build for you later today or early next week.
