### ISSUE TITLE
C00CE169 error because of InitialRotationPreference set to "any"

### ISSUE THREAD

**Issue by birbilis** [manifoldjs/manifoldjs-windows10#5]
Error   APPX0501    Validation error. error C00CE169: App manifest validation error: The app manifest must be valid as per schema: Line 41, Column 25, 

Reason (translated from Greek message): The 'any' breaks the constraint of the enumeration of 'portrait landscape portraitFlipped landscapeFlipped'. Analysis of the characteristic 'Preference' with value 'any' failed.   

Changing "any" to "portrait" at

```
    <uap:InitialRotationPreference>
      <uap:Rotation Preference="any" />
    </uap:InitialRotationPreference>
```

fixed this and so did commenting out the whole block in  too

I had used the visual tool to generate the manifest, so it should take care to not add "any". Maybe if any is selected it can remove or better comment out (with a value of portrait in it) the block for the preference altogether

**Comment by boyofgreen** [comment]
Hi Giorgio, by visual tool you mean manifoldjs.com generator?  We have this fix in but we haven't deployed it to the site yet, sorry about that.

**Comment by juliankay** [comment]
Still getting this error. As mentioned above, commenting out the `<uap:InitialRotationPreference>` block will fix the build, after that there were no issues.

**Comment by boyofgreen** [comment]
Thanks,
  We will be deploying change to the server before the end of the month.  Thanks for keeping us updated.

**Comment by birbilis** [comment]
> by visual tool you mean manifoldjs.com generator
> indeed, I was meaning the website generator
